[package]
name = "microstatus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
ping = "0.7"
rand = "0.9.2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] } 
